// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7YLx4aGukrEHsSO5qG-WmiyCZDu0nvlc',
    appId: '1:735638100178:web:a0c3a80bc877cfd6e2750b',
    messagingSenderId: '735638100178',
    projectId: 'documate-cff32',
    authDomain: 'documate-cff32.firebaseapp.com',
    storageBucket: 'documate-cff32.firebasestorage.app',
    measurementId: 'G-39P0PKPWYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr96pDsD-mlItLIVMnpAL6TLiRMY29PEc',
    appId: '1:735638100178:android:7e526545692b3ce6e2750b',
    messagingSenderId: '735638100178',
    projectId: 'documate-cff32',
    storageBucket: 'documate-cff32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxxnup4V_F6KqVR-d0pujywD_VrDrkaN8',
    appId: '1:735638100178:ios:906b08109f783990e2750b',
    messagingSenderId: '735638100178',
    projectId: 'documate-cff32',
    storageBucket: 'documate-cff32.firebasestorage.app',
    iosBundleId: 'com.example.documate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxxnup4V_F6KqVR-d0pujywD_VrDrkaN8',
    appId: '1:735638100178:ios:906b08109f783990e2750b',
    messagingSenderId: '735638100178',
    projectId: 'documate-cff32',
    storageBucket: 'documate-cff32.firebasestorage.app',
    iosBundleId: 'com.example.documate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7YLx4aGukrEHsSO5qG-WmiyCZDu0nvlc',
    appId: '1:735638100178:web:665443eece36ab43e2750b',
    messagingSenderId: '735638100178',
    projectId: 'documate-cff32',
    authDomain: 'documate-cff32.firebaseapp.com',
    storageBucket: 'documate-cff32.firebasestorage.app',
    measurementId: 'G-Y1WBZB3M3W',
  );
}
